services:

  redpanda:
    image: docker.redpanda.com/redpandadata/redpanda:v24.1.2
    container_name: redpanda

    command:
      - redpanda
      - start
      - --overprovisioned
      - --smp
      - "1"
      - --memory
      - 1G
      - --reserve-memory
      - 0M
      - --node-id
      - "0"
      - --check=false

    ports:
      - "9092:9092"
      - "9644:9644"

  uplift-api:
    build: .
    container_name: uplift-api

    ports:
      - "8001:8001"

    depends_on:
      - redpanda